version: "3.8"

services:
  
  MShop.catalago.dev:
    container_name: catalagoDb-dev
    hostname: catalagoDb-dev
    image: mariadb:10.6.3
    ports:
      - 3308:3306
    volumes:
      - "./mysql/data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "mshop"
      MYSQL_USER: "mshop"
      MYSQL_PASSWORD: "mshop"
      MYSQL_DATABASE: "mshop"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - app-catalago

  MShop.MongoDB.dev:
    image: mongo:6.0.5
    container_name: mongodb-dev
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    command: ["mongod", "--auth"]
    networks:
      - app-catalago
  
  Mshop.Rabbitmq.dev:
    container_name: rabbitmq-dev
    image: rabbitmq:3-management
    hostname: rabbitmq-dev
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
      - RABBITMQ_DEFAULT_VHOST=catalago
    volumes:
      - ./dateRabbitMQ:/var/lib/rabbitmq/
    ports:
      - 15672:15672 #potaHost : Porta Container
      - 5672:5672
    networks:
      - app-catalago

  MShop.Redis.dev:
   container_name: redis-dev
   hostname: redis-dev
   image: redislabs/redisearch:2.8.7
   ports:
     - "8378:6379" 
   networks:
     - app-catalago

  MShop.Keycloak.dev:
    container_name: keycloak-dev
    hostname: keycloak-dev
    image: quay.io/keycloak/keycloak:26.4 #https://quay.io/repository/keycloak/keycloak?tab=tags
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mariadb
      KC_DB_URL_HOST: catalagoDb-dev
      KC_DB_URL_PORT: 3306
      KC_DB_USERNAME: mshop
      KC_DB_PASSWORD: mshop
      KC_DB_URL_DATABASE: keycloak
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    command: 
      - start-dev --import-realm
    #command: start #use his command for production mode
    ports:
      - "8080:8080"
    depends_on:
      MShop.catalago.dev:
        condition: service_healthy
    networks:
      - app-catalago
  
  MShop.Elasticsearch.dev:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.1
    container_name: elasticsearch8
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true           # Habilita autenticação
      - xpack.security.transport.ssl.enabled=false
      - ELASTIC_PASSWORD=elasticpassword      # Senha do usuário padrão 'elastic'
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - app-catalago
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data # Persistência de dados
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
  
#  MShop.kibana.dev:
#    image: docker.elastic.co/kibana/kibana:8.10.1
#    container_name: kibana8
#    environment:
#      - ELASTICSEARCH_HOSTS=http://MShop.Elasticsearch.dev:9200
#      - ELASTICSEARCH_USERNAME=kibana_user        # Usuário do Elasticsearch
#      - ELASTICSEARCH_PASSWORD=kibana # Senha definida no Elasticsearch
#    ports:
#      - "5601:5601"
#    networks:
#      - app-catalago
#    depends_on:
#      - MShop.Elasticsearch.dev
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: 1024M

#  MShop.apm-server.dev:
#    image: docker.elastic.co/apm/apm-server:8.10.1
#    container_name: apm-server
#    depends_on:
#      - MShop.Elasticsearch.dev
#      - MShop.kibana.dev
#    ports:
#      - "8200:8200"
#    command: >
#      apm-server -e
#        -E apm-server.host=0.0.0.0:8200
#        -E output.elasticsearch.hosts=["http://MShop.Elasticsearch.dev:9200"]
#        -E output.elasticsearch.username=elastic
#        -E output.elasticsearch.password=elasticpassword
#    networks:
#      - app-catalago   


#  MShop.jaeger.dev:
#    image: jaegertracing/all-in-one:1.54
#    container_name: jaeger
#    ports:
#      - "16686:16686" # UI
#      - "14250:4317" # gRPC collector
#    environment:
#      - COLLECTOR_OTLP_ENABLED=true
#    networks:
#      - app-catalago
  
#  MShop.otel-collector.dev:
#    image: otel/opentelemetry-collector-contrib:0.96.0
#    container_name: otel-collector
#    depends_on:
#      - MShop.apm-server.dev
#    ports:
#      - "4317:4317" # OTLP gRPC
#      - "4318:4318" # OTLP HTTP
#    volumes:
#      - ./openTelemetry/config.yaml:/etc/otelcol/config.yaml
#    command: ["--config=/etc/otelcol/config.yaml"]
#    networks:
#      - app-catalago

  MShop.loki.dev:
    hostname: loki
    image: grafana/loki:3.6.7
    ports:
      - 3100:3100
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/config.yaml:ro
      - ./loki/data:/loki
    command: ['-config.file=/etc/loki/config.yaml']
    restart: unless-stopped
    networks:
      - app-catalago

  MShop.Grafana.dev:
    hostname: grafana
    image: grafana/grafana:12.4.0
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=508197
    volumes:
    #  - ./grafana/provisioning/datasources/default.yaml:/etc/grafana/provisioning/datasources/default.yaml:ro
      - ./grafana/provisioning/dashboards/default.yaml:/etc/grafana/provisioning/dashboards/default.yaml:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    restart: unless-stopped
    networks:
      - app-catalago
  
  MShop.Alloy.dev:
    container_name: alloy
    hostname: alloy
    image: grafana/alloy:v1.12.0
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - /etc/alloy/config.alloy
    ports:
      - 12345:12345   #admin/debug
      - 4317:4317     #gRPC
      - 4318:4318     #HTTP
    volumes:
      - ./alloy/alloy-config.alloy:/etc/alloy/config.alloy:ro
      #- /var/run/docker.sock:/var/run/docker.sock:ro // logs do docker
    restart: unless-stopped
    networks:
      - app-catalago

  MShop.Tempo.dev:
    image: grafana/tempo:2.7.2
    hostname: tempo
    ports:
      - "3200:3200"
    #  - "4319:4317"
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - ./tempo/data:/tmp/tempo
    restart: unless-stopped
    networks:
      - app-catalago
  
  MShop.Prometheus.dev:
    image: prom/prometheus:v3.5.0
    hostname: prometheus
    ports:
      - 9090:9090
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/data:/prometheus/data
    restart: unless-stopped
    networks:
      - app-catalago

volumes:
  elasticsearch:

networks:
  app-catalago:
    external: true