#!/bin/bash

curl -X POST "http://localhost:9200/_security/role/log_creator" -H "Content-Type: application/json" -u elastic:elasticpassword  -d '{
    "indices": [
      {
        "names": ["*"],
        "privileges": ["create_index", "write", "read","delete_index","manage","all"]
      }
    ]
  }'


#curl -X POST "http://localhost:9200/_security/role/kibana_custom_role" -H "Content-Type: application/json" -u elastic:elasticpassword -d '{
#  "cluster": ["all"],
#  "index": [
#    {
#      "names": [ "*" ],
#      "privileges": ["read", "write", "create_index", "view_index_metadata", "manage"]
#    }
# ]
#}'


curl -X POST "http://localhost:9200/_security/user/kibana_user" -H "Content-Type: application/json" -u elastic:elasticpassword -d '{
    "password": "kibana",
    "roles": ["kibana_system","kibana_admin","log_creator"],
    "full_name": "kibana_user",
    "email": "kibana@example.com"
  }'