apiVersion: 1

datasources:

#  - name: Mimir
#    uid: mimir
#    type: prometheus
#    access: proxy
#    url: http://mimir:9009/prometheus
#    isDefault: true
#    jsonData:
#      httpMethod: POST
#      prometheusType: Mimir
#      manageAlerts: true

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100

#  - name: Tempo
#    uid: tempo
#    type: tempo
#    access: proxy
#    url: http://tempo:3200
#    jsonData:
#      serviceMap:
#        datasourceUid: mimir
#      nodeGraph:
#        enabled: true