documentacao API

### Get Access Token for User admin
POST  http://localhost:8080/realms/ecommerce/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

username=admin
&password=123456
&grant_type=password
&client_id=web-app
&scope=openid


### Get Access Token for User
POST  http://localhost:8080/realms/ecommerce/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

username=dev
&password=123456
&grant_type=password
&client_id=web-app
&scope=openid
# essa opção tem que esta marcado no client Direct access grant


### get token acess esse token e usado no microserviços para validar o jwt se foi criado no keycloak
# @name auth
POST http://localhost:8080/realms/ecommerce/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=api-customer-admin
&client_secret=hmyqNSACk1XYNvMcwWYW2Yscn4JZlTPW
&grant_type=client_credentials


###############################################
### 2) PEGAR O ACCESS TOKEN AUTOMATICAMENTE ###
###############################################
@token = {{auth.response.body.access_token}}


###create user in keycloak
POST http://localhost:8080/admin/realms/ecommerce/users
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "username": "davi",
  "email": "marckvaldo@hotmail.com",
  "enabled": true,
  "firstName": "João",
  "lastName": "Silva",
  "emailVerified": false,
  "credentials": [
    {
      "type": "password",
      "value": "91020410@Php",
      "temporary": false
    }
  ]
}


### obtem o usuario por email
GET http://localhost:8080/admin/realms/ecommerce/users?email=marckvaldo@hotmail.com
Authorization: Bearer {{token}}


### set useId
@userId = 9dd2fbf1-33c8-4c5c-a5b3-7fddc7ac35ca

###send verification emailto user
PUT http://localhost:8080/admin/realms/ecommerce/users/{{userId}}/execute-actions-email
Authorization: Bearer {{token}}
Content-Type: application/json

[
  "VERIFY_EMAIL"
]


### list groups
GET http://localhost:8080/admin/realms/ecommerce/groups
Authorization: Bearer {{token}}

### search group
GET http://localhost:8080/admin/realms/ecommerce/groups?search=customer
Authorization: Bearer {{token}}

### set groupId
@groupId = 53b95ab8-5a8b-485c-ad81-45feda20d25d

### add user to group
PUT http://localhost:8080/admin/realms/ecommerce/users/{{userId}}/groups/{{groupId}}
Authorization: Bearer {{token}}


### get public key
GET http://localhost:8080/realms/ecommerce/protocol/openid-connect/certs






